services:
  - type: web
    name: vattunhatho
    runtime: docker
    plan: free
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_EMAIL
        sync: false
      - key: GOOGLE_PRIVATE_KEY
        sync: false
